# .github/workflows/ci.yml
# Comprehensive CI for all supported platforms

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # macOS and Apple Platforms
  build-macos:
    runs-on: macos-14
    name: macOS (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Show versions
        run: |
          xcodebuild -version
          swift --version
      - name: Clean build directory
        run: rm -rf .build
      - name: Build and Test
        run: |
          swift build -v
          swift test -v

  build-ios:
    runs-on: macos-14
    name: iOS (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Clean build directory
        run: rm -rf .build
      - name: Build and Test
        run: |
          xcodebuild -scheme genetic-solver -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build test

  build-tvos:
    runs-on: macos-14
    name: tvOS (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Clean build directory
        run: rm -rf .build
      - name: Build and Test
        run: |
          xcodebuild -scheme genetic-solver -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=latest' build test

  build-visionos:
    runs-on: macos-14
    name: visionOS (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Clean build directory
        run: rm -rf .build
      - name: Build and Test
        run: |
          xcodebuild -scheme genetic-solver -destination 'platform=visionOS Simulator,name=Apple Vision Pro,OS=latest' build test

  # Linux
  build-linux:
    runs-on: ubuntu-latest
    name: Linux (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Show Swift version
        run: swift --version
      - name: Build and Test
        run: |
          swift build -v
          swift test -v

  build-linux-release:
    runs-on: ubuntu-latest
    name: Linux Release (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Show Swift version
        run: swift --version
      - name: Build and Test Release
        run: |
          swift build -c release -v
          swift test -c release -v

  # Windows
  build-windows:
    runs-on: windows-2022
    name: Windows (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Verify Swift installation
        run: |
          swift --version
          swift build --help
        shell: pwsh
      - name: Build and Test
        run: |
          swift build -v
          swift test -v
        shell: pwsh

  build-windows-release:
    runs-on: windows-2022
    name: Windows Release (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Verify Swift installation
        run: |
          swift --version
          swift build --help
        shell: pwsh
      - name: Build and Test Release
        run: |
          swift build -c release -v
          swift test -c release -v
        shell: pwsh
