# .github/workflows/linux.yml
# CI for Swift packages on Linux.

name: Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build and Test (Linux)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

  build-linux-release:
    runs-on: ubuntu-latest
    name: Build and Test (Linux Release)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Show Swift version
        run: swift --version

      - name: Build Release
        run: swift build -c release -v

      - name: Test Release
        run: swift test -c release -v
