# .github/workflows/swift.yml
# CI for Swift packages on macOS 15 + Xcode 16.4 (latest-stable).

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read      # least-privilege for CI

jobs:
  build:
    runs-on: macos-15      # macOS 15 “Sequoia” runner (GA Apr 2025)

    steps:
      # 1 – Check out sources
      - uses: actions/checkout@v4

      # 2 – Select newest *stable* Xcode pre-installed on this image
      - name: Select Xcode (latest-stable)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable   # resolves to Xcode 16.4 today

      # 3 – (Optional) pin a Swift toolchain version
      # - uses: swift-actions/setup-swift@v2
      #   with:
      #     swift-version: "6.1"

      # 4 – Build and test
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
