# .github/workflows/swift.yml
# Swift-specific CI workflow

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-14
    name: Build and Test (macOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for macOS
        run: swift build -v

      - name: Test for macOS
        run: swift test -v

  build-ios:
    runs-on: macos-14
    name: Build and Test (iOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for iOS
        run: swift build -v --triple arm64-apple-ios13.0

      - name: Test for iOS
        run: swift test -v --triple arm64-apple-ios13.0

  build-tvos:
    runs-on: macos-14
    name: Build and Test (tvOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for tvOS
        run: swift build -v --triple arm64-apple-tvos13.0

      - name: Test for tvOS
        run: swift test -v --triple arm64-apple-tvos13.0

  build-visionos:
    runs-on: macos-14
    name: Build and Test (visionOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for visionOS
        run: swift build -v --triple arm64-apple-visionos1.0

      - name: Test for visionOS
        run: swift test -v --triple arm64-apple-visionos1.0
