# .github/workflows/swift.yml
# Swift-specific CI workflow

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-14
    name: Build and Test (macOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Clean build directory
        run: rm -rf .build

      - name: Build for macOS
        run: swift build -v

      - name: Test for macOS
        run: swift test -v

  build-ios:
    runs-on: macos-14
    name: Build and Test (iOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Clean build directory
        run: rm -rf .build

      - name: Build and Test for iOS
        run: xcodebuild -scheme genetic-solver -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build test

  build-tvos:
    runs-on: macos-14
    name: Build and Test (tvOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Clean build directory
        run: rm -rf .build

      - name: Build and Test for tvOS
        run: xcodebuild -scheme genetic-solver -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=latest' build test

  build-visionos:
    runs-on: macos-14
    name: Build and Test (visionOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Clean build directory
        run: rm -rf .build

      - name: Build and Test for visionOS
        run: xcodebuild -scheme genetic-solver -destination 'platform=visionOS Simulator,name=Apple Vision Pro,OS=latest' build test
