# .github/workflows/swift.yml
# CI for Swift packages on macOS 14 + Xcode 15.2.

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read      # least-privilege for CI

jobs:
  build-macos:
    runs-on: macos-14
    name: Build and Test (macOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      # 1 – Check out sources
      - uses: actions/checkout@v4

      # 2 – Select Xcode 15.2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      # 3 – Install Swift
      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      # 4 – Show versions
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Show Swift version
        run: swift --version

      # 5 – Build and test
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  build-ios:
    runs-on: macos-14
    name: Build and Test (iOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for iOS
        run: |
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          swift build -v --triple arm64-apple-ios13.0 -sdk $SDK

      - name: Test for iOS
        run: |
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          swift test -v --triple arm64-apple-ios13.0 -sdk $SDK

  build-tvos:
    runs-on: macos-14
    name: Build and Test (tvOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for tvOS
        run: |
          SDK=$(xcrun --sdk appletvos --show-sdk-path)
          swift build -v --triple arm64-apple-tvos13.0 -sdk $SDK

      - name: Test for tvOS
        run: |
          SDK=$(xcrun --sdk appletvos --show-sdk-path)
          swift test -v --triple arm64-apple-tvos13.0 -sdk $SDK

  build-visionos:
    runs-on: macos-14
    name: Build and Test (visionOS)
    strategy:
      matrix:
        swift-version: [5.9, 6.1.2]

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build for visionOS
        run: |
          SDK=$(xcrun --sdk xros --show-sdk-path)
          swift build -v --triple arm64-apple-visionos1.0 -sdk $SDK

      - name: Test for visionOS
        run: |
          SDK=$(xcrun --sdk xros --show-sdk-path)
          swift test -v --triple arm64-apple-visionos1.0 -sdk $SDK
